language: php


php:

  - 5.4

  - 5.5

  - 5.6

  - 7.0

  - hhvm


matrix:

  allow_failures:

    - php: hhvm


before_script:

  - "mysql -e 'create database `ucenter`;'"
  - composer self-update
  - composer install -n --prefer-source

  - ./vendor/bin/codecept build


script:

  - ./vendor/bin/codecept run
